### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by dbottini2022pioix** [PioIX/G11-TPI-1Cuat#1]
Idea: un juego de comandos donde somos una persona que reduce el hambre dandole de comer a las personas. A su vez vamos bajando el contador de hambre.

**Comment by dbottini2022pioix** [comment]
Quizás enfocarnos más en las causas que en entregar comida sea mejor para profundizar y captar más del ODS del hambre.

**Comment by fedsalga** [comment]
Idea de Ian: hacer un juego donde somos un tacho de basura el cual agarra la basura que cae del cielo.
